slice: add SliceCompare function
harvester/go-common pull request #8
Opened 2023-12-13 08:01 UTC by Vicente-Cheng

2023-12-13 08:55 UTC, bk201 commented on slice.go
> +func SliceCompare[T comparable](x, y []T) bool {
Can we add some documents for both functions?

2023-12-13 09:07 UTC, Vicente-Cheng commented on slice.go
> +func SliceCompare[T comparable](x, y []T) bool {
Thanks for the reminder! Updated!

2023-12-14 03:49 UTC, FrankYang0529 requested changes

2023-12-14 03:49 UTC, FrankYang0529 commented on slice_test.go
> +}
This function can't handle following case:

```go
	g := []int{1, 1, 2}
	h := []int{1, 2, 2}
	s.Equal(false, SliceCompare(g, h), "SliceCompare should return false")
```

2023-12-14 04:12 UTC, Vicente-Cheng commented on slice_test.go
> +}
Nice catch! Updated!

2023-12-14 06:38 UTC, FrankYang0529 requested changes

2023-12-14 06:38 UTC, FrankYang0529 commented on slice.go
> +	}
In golang, the slice header contains a pointer to the start of the array. If we modify input, we also update user's content. It's better to copy it first.

```go
    yCpy := make([]T, len(y))
	copy(yCpy, y)
	for _, xItem := range x {
		found := false
		for id, yItem := range yCpy {
			if xItem == yItem {
				yCpy = slices.Delete(yCpy, id, id+1)
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
```

2023-12-14 06:38 UTC, FrankYang0529 commented on slice_test.go
> +	s.Equal(false, SliceCompare(g, h), "SliceCompare should return false")
Also, we can test whether input is updated here.

```go
	gCpy := []int{1, 1, 2}
	hCpy := []int{1, 2, 2}

    // ...
    s.Equal(false, SliceCompare(g, h), "SliceCompare should return false")
	s.Equal(true, reflect.DeepEqual(g, gCpy), "SliceCompare should not update input")
	s.Equal(true, reflect.DeepEqual(h, hCpy), "SliceCompare should not update input")
```

2023-12-14 07:13 UTC, Vicente-Cheng commented on slice.go
> +	}
Updated! Thanks for the review!

2023-12-14 07:18 UTC, FrankYang0529 approved these changes
LGTM. Thanks!

2023-12-14 09:16 UTC, FrankYang0529 approved these changes
LGTM. Thanks.

2023-12-14 09:32 UTC, bk201 approved these changes

2023-12-14 09:35 UTC, merged